import React from "react";
import { createMetadata } from "@/lib/seo/metadata";
import { JsonLd, getBreadcrumbSchema } from "@/lib/seo/json-ld";

export const metadata = createMetadata({
  title: "Terms of Service — LegalGPT",
  description: "Terms and conditions governing the use of the LegalGPT contract intelligence platform.",
  path: "/terms",
  noindex: false,
});

export default function TermsPage() {
  return (
    <>
      <JsonLd
        schema={getBreadcrumbSchema([
          { label: "Home", href: "/" },
          { label: "Terms of Service", href: "/terms" },
        ])}
      />
      <div className="py-20 md:py-28 relative z-10">
        <div className="max-w-[800px] mx-auto px-6">
          <h1 className="text-3xl sm:text-5xl font-extrabold text-white mb-4">Terms of Service</h1>
          <p className="text-silver text-xs font-mono mb-12">Last Updated: March 2026</p>

          <div className="space-y-8 text-silver text-sm leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-white mb-3">1. Nature of the Service</h2>
              <p>
                LegalGPT is an AI-powered software application designed for informational contract review, risk analysis, and clause redlining assistance. LegalGPT is not a law firm, does not provide legal representation, and does not establish an attorney-client relationship.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">2. User Data and Confidentiality</h2>
              <p>
                You retain full and sole ownership of all documents, text, and files you upload to LegalGPT. We do not use your confidential contract text to train public machine learning models. Uploaded materials are processed in memory and governed by our Privacy Policy.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">3. Disclaimer of Legal Advice</h2>
              <p>
                The outputs generated by LegalGPT (including risk ratings, executive summaries, and substitute clauses) are automated machine interpretations. They should be used as reference tools for negotiation and review, not as a substitute for professional legal advice from a licensed attorney in your jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-white mb-3">4. Limitation of Liability</h2>
              <p>
                To the maximum extent permitted by applicable law, LegalGPT and its creators shall not be liable for any indirect, incidental, or consequential damages resulting from contract negotiations, business decisions, or agreements executed by you.
              </p>
            </section>
          </div>
        </div>
      </div>
    </>
  );
}
