import React from "react";
import { Scale, AlertTriangle } from "lucide-react";
import { createMetadata } from "@/lib/seo/metadata";
import { JsonLd, getBreadcrumbSchema } from "@/lib/seo/json-ld";

export const metadata = createMetadata({
  title: "Legal Disclaimer — LegalGPT",
  description: "Important legal disclaimers regarding the AI contract review features of LegalGPT.",
  path: "/disclaimer",
  noindex: false,
});

export default function DisclaimerPage() {
  return (
    <>
      <JsonLd
        schema={getBreadcrumbSchema([
          { label: "Home", href: "/" },
          { label: "Disclaimer", href: "/disclaimer" },
        ])}
      />
      <div className="py-20 md:py-28 relative z-10">
        <div className="max-w-[800px] mx-auto px-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#201815] border border-risk-medium/30 text-risk-medium mb-6 text-xs font-mono">
            <AlertTriangle className="w-3.5 h-3.5" />
            <span>Not an Attorney-Client Relationship</span>
          </div>

          <h1 className="text-3xl sm:text-5xl font-extrabold text-white mb-6">Legal Disclaimer</h1>

          <div className="rounded-2xl bg-surface/60 border border-edge p-8 mb-10 text-silver text-sm space-y-4 leading-relaxed">
            <p className="text-white font-medium">
              LegalGPT is an artificial intelligence-assisted legal technology software tool. The information, scores, summaries, redlines, and chat outputs generated by LegalGPT are intended solely for educational, workflow productivity, and informational purposes.
            </p>
            <p>
              LegalGPT does not offer formal legal advice, legal opinions, recommendations on rights, or formal attorney representation. No attorney-client relationship is created or implied by your use of this software, website, or associated services.
            </p>
            <p>
              Contract law is highly contextual and differs across jurisdictions, states, and court venues. Users should never substitute automated AI assessments for personalized legal review by a qualified attorney licensed in their governing jurisdiction.
            </p>
          </div>

          <div className="flex items-center gap-3 text-silver text-xs">
            <Scale className="w-4 h-4 text-accent" />
            <span>Questions regarding this policy can be directed to legal@legalgpt.ai</span>
          </div>
        </div>
      </div>
    </>
  );
}
